name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DEPLOY_SERVER }}" >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -rav --delete bot deploy@${{ secrets.DEPLOY_SERVER }}:/app/ban_mod_bot/
      - name: Install Systemd service
        run: |
          cp /app/ban_mod_bot/etc/systemd/ban_mod_bot.service /etc/systemd/system/
          sudo systemctl restart ban_mod_bot.service