name: Test
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Prepare env
        run: mv .env.test .env
      - name: Lint
        run: make lint
      - name: Test
        run: make test
