name: Test
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare env
        run: mv .env.test .env
      - name: Test
        run: make test

  lint:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare env
        run: mv .env.test .env
      - name: Lint
        run: make lint
